name: viltage
version: 0.2.0+15
author: ViliX64 <vilem.zouhar@gmail.com>
description: ViliX's Text/ASCII Game Engine
homepage: https://github.com/ViliX64/VilTAGE
environment:
  sdk: '>=1.6.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  crypto: '>=0.9.0 <1.0.0'
